#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[aliases]
cm = ["commit"]
init = ["git", "init", "--colocate"]
adv = ["bookmark", "set", "-r", "@-"]
push = ["git", "push", "--bookmark"]
fetch = ["git", "fetch"]
main = ["bookmark", "set", "main", "-r", "main@origin"]
sq = ["squash"]
cp = ["sq --from"]

[user]
name = "csepulveda-dev"
email = "github@accounts.camilosep.com"

[remotes.origin]
auto-track-bookmarks = "main"
